### ISSUE TITLE
S3 putObject with checksumAlgorithm gives missing Content Length error

### ISSUE THREAD

**Issue by erikvanoosten** [zio/zio-aws#1007]
Using s3 putObject, e.g. as follows:

```scala
  val bucket: String = ???
  val key: String = ???
  val length: Long = ???
  val inputStream: ZStream[Any, Throwable, Byte] = ???
  val request = PutObjectRequest(
          bucket = BucketName(bucket),
          key = ObjectKey(key),
          contentLength = Present(ContentLength(length)),
          checksumAlgorithm = Present(zio.aws.s3.model.ChecksumAlgorithm.SHA256)
        )
  storage.putObject(request, inputStream.mapError(AwsError.fromThrowable))
```
Results in a `software.amazon.awssdk.core.exception.SdkClientException: Content length must be supplied.` (full stack trace below). Note that the content length of the byte stream _is_ set. Our hypothesis is that the HTTP trailer with the checksum is missing a content length.

We are not sure if this is a bug or that we are using the API wrong.

Note, we're using the http4s client.

SBT dependencies:
```
      "dev.zio" %% "zio" % "2.0.3",
      "dev.zio" %% "zio-streams" % "2.0.3",
      "dev.zio" %% "zio-aws-s3" % "5.17.295.1",
      "dev.zio" %% "zio-aws-http4s" % "5.17.295.1",
```

```
software.amazon.awssdk.core.exception.SdkClientException: Content length must be supplied.
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:102)
        at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.doExecute(BaseAsyncClientHandler.java:247)
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.lambda$execute$1(BaseAsyncClientHandler.java:82)
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.measureApiCallSuccess(BaseAsyncClientHandler.java:291)
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.execute(BaseAsyncClientHandler.java:75)
        at software.amazon.awssdk.awscore.client.handler.AwsAsyncClientHandler.execute(AwsAsyncClientHandler.java:52)
        at software.amazon.awssdk.services.s3.DefaultS3AsyncClient.putObject(DefaultS3AsyncClient.java:10228)
        at ...elided...
Caused by: java.lang.UnsupportedOperationException: Content length must be supplied.
        at software.amazon.awssdk.core.internal.async.ChecksumCalculatingAsyncRequestBody.lambda$new$0(ChecksumCalculatingAsyncRequestBody.java:62)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at software.amazon.awssdk.core.internal.async.ChecksumCalculatingAsyncRequestBody.<init>(ChecksumCalculatingAsyncRequestBody.java:62)
        at software.amazon.awssdk.core.internal.async.ChecksumCalculatingAsyncRequestBody.<init>(ChecksumCalculatingAsyncRequestBody.java:43)
        at software.amazon.awssdk.core.internal.async.ChecksumCalculatingAsyncRequestBody$DefaultBuilder.build(ChecksumCalculatingAsyncRequestBody.java:108)
        at software.amazon.awssdk.core.internal.async.ChecksumCalculatingAsyncRequestBody$DefaultBuilder.build(ChecksumCalculatingAsyncRequestBody.java:99)
        at software.amazon.awssdk.core.internal.interceptor.AsyncRequestBodyHttpChecksumTrailerInterceptor.modifyAsyncHttpContent(AsyncRequestBodyHttpChecksumTrailerInterceptor.java:71)
        at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyHttpRequestAndHttpContent(ExecutionInterceptorChain.java:88)
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.runModifyHttpRequestAndHttpContentInterceptors(BaseClientHandler.java:155)
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:82)
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.doExecute(BaseAsyncClientHandler.java:201)
        ... 28 common frames omitted

```

**Comment by erikvanoosten** [comment]
Using the netty client gives the same result.

**Comment by vigoo** [comment]
Interesting. Have you ever used this directly with the Java SDK? 
As zio-aws is calling that and not directly composing the requests, I would assume it has the same behavior.

**Comment by erikvanoosten** [comment]
> Have you ever used this directly with the Java SDK?

Nope, I have never used the java sdk. Actually, this is the first time I am using an AWS api from code.

**Comment by vigoo** [comment]
Found this: https://github.com/aws/aws-sdk-java-v2/issues/3429 which is not the same issue but it states that the java library's `S3TransferManager` (which is a higher level API in it than what `zio-aws-s3` is calling) so I think we should check how that calls the underlying `PutObject` exactly.

**Comment by erikvanoosten** [comment]
According to https://github.com/aws/aws-sdk-java-v2/issues/3429#issuecomment-1249605593, it seems that this feature is not yet supported in the SDK.

**Comment by erikvanoosten** [comment]
Hmm, then again. According to https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/ it should be available...

**Comment by vigoo** [comment]
This seems to be the implementation: https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/interceptor/AsyncRequestBodyHttpChecksumTrailerInterceptor.java

the question is whether this interceptor runs in your case (or in any case when using zio-aws) and if not, how to enable it. I would expect it to "just work" as really zio-aws is just a different view of the public java API but maybe there is a difference in how the wrapper sets up the request and what they expect.. need to dig deeper 

If you have a chance to debug your code, could you check if it runs into that interceptor at all?

**Comment by erikvanoosten** [comment]
👍 Thanks for finding that. I will check today.

**Comment by erikvanoosten** [comment]
*Observations*

On this line: https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/ChecksumCalculatingAsyncRequestBody.java#L61-L62
Field `wrapped` is set to an instance of type `zio.aws.core.ZStreamAsyncRequestBody` (see screenshot)
<img width="727" alt="Schermafbeelding 2022-11-10 om 14 53 20" src="https://user-images.githubusercontent.com/630600/201109880-7d7514bc-45b7-486c-bfb1-b87c78b776b1.png">

`ZStreamAsyncRequestBody` has the following line: `def contentLength(): Optional[lang.Long] = Optional.empty()` so it will never return the length.

*Discussion*

I find it very weird that the length needs to be known up-front. Sounds very non-async to me.

*Work-around*

Regardless, we can work-around this limitation when the size is known in the request (which indeed it is in my use case).
On line https://github.com/zio/zio-aws/blob/master/zio-aws-core/src/main/scala/zio/aws/core/AwsServiceBase.scala#L192 (and perhaps https://github.com/zio/zio-aws/blob/master/zio-aws-core/src/main/scala/zio/aws/core/AwsServiceBase.scala#L217 as well) we can pass the content-length from the request parameter to the `ZStreamAsyncRequestBody`.

I'll try it out locally and send a PR if it works.

**Comment by erikvanoosten** [comment]
Interesting comment regarding requiring content-length up front:
https://github.com/aws/aws-sdk-java-v2/issues/2431#issuecomment-825922346

**Comment by Giov097** [comment]
I'm having the same issue with PutObjectRequest API in Java, and with UploadPartRequest as well. Even though I'm specifying the content-length header, it asks for the content length when trying to use the checksum algorithm one.
